# Generated by Django 5.0.2 on 2025-11-24 13:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_mushroomimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mushroomimage',
            name='image',
            field=models.ImageField(help_text='Upload a clear image of the mushroom (JPG, JPEG, or PNG)', upload_to='static/unknown_mushrooms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='mushroom image'),
        ),
        migrations.AlterField(
            model_name='unknownmushroom',
            name='image',
            field=models.ImageField(upload_to='static/unknown_mushrooms/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
